#############################################################################
# Makefile for building: MeshViewer
# Generated by qmake (3.1) (Qt 5.9.6)
# Project:  MeshViewer.pro
# Template: app
# Command: /home/oalexan1/miniconda3/envs/isis5.0.1/bin/qmake -o Makefile MeshViewer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../assimp/include -I../assimp/build/include -I../../miniconda3/envs/isis5.0.1/include/qt -I../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets -I../../miniconda3/envs/isis5.0.1/include/qt/QtGui -I../../miniconda3/envs/isis5.0.1/include/qt/QtCore -I. -I. -I../../miniconda3/envs/isis5.0.1/mkspecs/linux-g++
QMAKE         = /home/oalexan1/miniconda3/envs/isis5.0.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/oalexan1/miniconda3/envs/isis5.0.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/oalexan1/miniconda3/envs/isis5.0.1/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MeshViewer1.0.0
DISTDIR = /home/oalexan1/projects/Mesh-Viewer/.tmp/MeshViewer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/oalexan1/miniconda3/envs/isis5.0.1/lib
LIBS          = $(SUBLIBS) -L/home/oalexan1/projects/assimp/build/bin -lassimp -lglut -lGLU -L/home/oalexan1/miniconda3/envs/isis5.0.1/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		openglwindow.cpp \
		modelmanager.cpp moc_mainwindow.cpp \
		moc_openglwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		openglwindow.o \
		modelmanager.o \
		moc_mainwindow.o \
		moc_openglwindow.o
DIST          = ../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_pre.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/linux.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/sanitize.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base-unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-base.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/qconfig.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_input_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_service_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uiplugin.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_functions.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_config.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/linux-g++/qmake.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/exclusive_builds.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/toolchain.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/default_pre.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/resolve_config.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/default_post.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/warn_on.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/resources.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/moc.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/opengl.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/uic.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/thread.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qmake_use.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/file_copies.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/testcase_targets.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/exceptions.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/yacc.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/lex.prf \
		MeshViewer.pro mainwindow.h \
		openglwindow.h \
		modelmanager.h main.cpp \
		mainwindow.cpp \
		openglwindow.cpp \
		modelmanager.cpp
QMAKE_TARGET  = MeshViewer
DESTDIR       = 
TARGET        = MeshViewer


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MeshViewer.pro ../../miniconda3/envs/isis5.0.1/mkspecs/linux-g++/qmake.conf ../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_pre.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/linux.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/sanitize.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base-unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-base.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-unix.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/qconfig.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_input_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_service_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uiplugin.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_functions.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_config.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/linux-g++/qmake.conf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/exclusive_builds.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/toolchain.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/default_pre.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/resolve_config.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/default_post.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/warn_on.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qt.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/resources.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/moc.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/opengl.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/uic.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/thread.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/qmake_use.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/file_copies.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/testcase_targets.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/exceptions.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/yacc.prf \
		../../miniconda3/envs/isis5.0.1/mkspecs/features/lex.prf \
		MeshViewer.pro \
		../../miniconda3/envs/isis5.0.1/lib/libQt5Widgets.prl \
		../../miniconda3/envs/isis5.0.1/lib/libQt5Gui.prl \
		../../miniconda3/envs/isis5.0.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MeshViewer.pro
../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_pre.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/unix.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/linux.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/sanitize.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/gcc-base-unix.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-base.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/common/g++-unix.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/qconfig.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_charts_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_concurrent_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_core_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_dbus_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designer_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fb_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gamepad_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_glx_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_gui_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_help_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_input_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimedia_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_network_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_networkauth_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_nfc_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_opengl_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_printsupport_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_purchasing_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qml_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qmltest_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quick_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_repparser_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_script_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scripttools_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_scxml_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_service_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_sql_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_svg_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_testlib_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_theme_support_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uiplugin.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_uitools_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_webchannel_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_websockets_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_widgets_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_x11extras_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xml_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_functions.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/qt_config.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/linux-g++/qmake.conf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/spec_post.prf:
.qmake.stash:
../../miniconda3/envs/isis5.0.1/mkspecs/features/exclusive_builds.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/toolchain.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/default_pre.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/resolve_config.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/default_post.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/warn_on.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/qt.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/resources.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/moc.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/opengl.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/uic.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/unix/thread.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/qmake_use.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/file_copies.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/testcase_targets.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/exceptions.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/yacc.prf:
../../miniconda3/envs/isis5.0.1/mkspecs/features/lex.prf:
MeshViewer.pro:
../../miniconda3/envs/isis5.0.1/lib/libQt5Widgets.prl:
../../miniconda3/envs/isis5.0.1/lib/libQt5Gui.prl:
../../miniconda3/envs/isis5.0.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MeshViewer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../miniconda3/envs/isis5.0.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h openglwindow.h modelmanager.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp openglwindow.cpp modelmanager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../miniconda3/envs/isis5.0.1/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../miniconda3/envs/isis5.0.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_openglwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_openglwindow.cpp
moc_mainwindow.cpp: ../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QMainWindow \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qmainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtabwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qicon.h \
		mainwindow.h \
		moc_predefs.h \
		../../miniconda3/envs/isis5.0.1/bin/moc
	/home/oalexan1/miniconda3/envs/isis5.0.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/oalexan1/miniconda3/envs/isis5.0.1/mkspecs/linux-g++ -I/home/oalexan1/projects/Mesh-Viewer -I/home/oalexan1/projects/assimp/include -I/home/oalexan1/projects/assimp/build/include -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtWidgets -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtGui -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtCore -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_openglwindow.cpp: ../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QOpenGLWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qopenglwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QSurfaceFormat \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qsurfaceformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qt_windows.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengles2ext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopenglext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QKeyEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QMouseEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QWheelEvent \
		modelmanager.h \
		../assimp/include/assimp/cimport.h \
		../assimp/include/assimp/importerdesc.h \
		../assimp/include/assimp/types.h \
		../assimp/include/assimp/defs.h \
		../assimp/build/include/assimp/config.h \
		../assimp/include/assimp/vector2.h \
		../assimp/include/assimp/vector3.h \
		../assimp/include/assimp/color4.h \
		../assimp/include/assimp/matrix3x3.h \
		../assimp/include/assimp/matrix4x4.h \
		../assimp/include/assimp/quaternion.h \
		../assimp/include/assimp/vector2.inl \
		../assimp/include/assimp/vector3.inl \
		../assimp/include/assimp/color4.inl \
		../assimp/include/assimp/matrix3x3.inl \
		../assimp/include/assimp/matrix4x4.inl \
		../assimp/include/assimp/MathFunctions.h \
		../assimp/include/assimp/quaternion.inl \
		../assimp/include/assimp/postprocess.h \
		../assimp/include/assimp/scene.h \
		../assimp/include/assimp/texture.h \
		../assimp/include/assimp/Compiler/pushpack1.h \
		../assimp/include/assimp/Compiler/poppack1.h \
		../assimp/include/assimp/mesh.h \
		../assimp/include/assimp/aabb.h \
		../assimp/include/assimp/light.h \
		../assimp/include/assimp/camera.h \
		../assimp/include/assimp/material.h \
		../assimp/include/assimp/material.inl \
		../assimp/include/assimp/anim.h \
		../assimp/include/assimp/metadata.h \
		../assimp/include/assimp/Compiler/pstdint.h \
		openglwindow.h \
		moc_predefs.h \
		../../miniconda3/envs/isis5.0.1/bin/moc
	/home/oalexan1/miniconda3/envs/isis5.0.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/oalexan1/miniconda3/envs/isis5.0.1/mkspecs/linux-g++ -I/home/oalexan1/projects/Mesh-Viewer -I/home/oalexan1/projects/assimp/include -I/home/oalexan1/projects/assimp/build/include -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtWidgets -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtGui -I/home/oalexan1/miniconda3/envs/isis5.0.1/include/qt/QtCore -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include openglwindow.h -o moc_openglwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../miniconda3/envs/isis5.0.1/bin/uic \
		openglwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QOpenGLWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qopenglwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QSurfaceFormat \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qsurfaceformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qt_windows.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengles2ext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopenglext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QKeyEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QMouseEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QWheelEvent \
		modelmanager.h \
		../assimp/include/assimp/cimport.h \
		../assimp/include/assimp/importerdesc.h \
		../assimp/include/assimp/types.h \
		../assimp/include/assimp/defs.h \
		../assimp/build/include/assimp/config.h \
		../assimp/include/assimp/vector2.h \
		../assimp/include/assimp/vector3.h \
		../assimp/include/assimp/color4.h \
		../assimp/include/assimp/matrix3x3.h \
		../assimp/include/assimp/matrix4x4.h \
		../assimp/include/assimp/quaternion.h \
		../assimp/include/assimp/vector2.inl \
		../assimp/include/assimp/vector3.inl \
		../assimp/include/assimp/color4.inl \
		../assimp/include/assimp/matrix3x3.inl \
		../assimp/include/assimp/matrix4x4.inl \
		../assimp/include/assimp/MathFunctions.h \
		../assimp/include/assimp/quaternion.inl \
		../assimp/include/assimp/postprocess.h \
		../assimp/include/assimp/scene.h \
		../assimp/include/assimp/texture.h \
		../assimp/include/assimp/Compiler/pushpack1.h \
		../assimp/include/assimp/Compiler/poppack1.h \
		../assimp/include/assimp/mesh.h \
		../assimp/include/assimp/aabb.h \
		../assimp/include/assimp/light.h \
		../assimp/include/assimp/camera.h \
		../assimp/include/assimp/material.h \
		../assimp/include/assimp/material.inl \
		../assimp/include/assimp/anim.h \
		../assimp/include/assimp/metadata.h \
		../assimp/include/assimp/Compiler/pstdint.h
	/home/oalexan1/miniconda3/envs/isis5.0.1/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QMainWindow \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qmainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtabwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qicon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QApplication \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qeventloop.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qdesktopwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qguiapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QMainWindow \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qmainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtabwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qicon.h \
		ui_mainwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/QVariant \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QAction \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qaction.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qactiongroup.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QApplication \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qeventloop.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qdesktopwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qguiapplication.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qinputmethod.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QButtonGroup \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qbuttongroup.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QHeaderView \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qheaderview.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qabstractitemview.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qabstractscrollarea.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qframe.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qabstractitemmodel.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qitemselectionmodel.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qabstractitemdelegate.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qstyleoption.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qabstractspinbox.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvalidator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregularexpression.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qslider.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qabstractslider.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qstyle.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtabbar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qrubberband.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QMenu \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qmenu.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QMenuBar \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qmenubar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QStatusBar \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qstatusbar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QToolBar \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtoolbar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QWidget \
		openglwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QOpenGLWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qopenglwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QSurfaceFormat \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qsurfaceformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qt_windows.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengles2ext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopenglext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QKeyEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QMouseEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QWheelEvent \
		modelmanager.h \
		../assimp/include/assimp/cimport.h \
		../assimp/include/assimp/importerdesc.h \
		../assimp/include/assimp/types.h \
		../assimp/include/assimp/defs.h \
		../assimp/build/include/assimp/config.h \
		../assimp/include/assimp/vector2.h \
		../assimp/include/assimp/vector3.h \
		../assimp/include/assimp/color4.h \
		../assimp/include/assimp/matrix3x3.h \
		../assimp/include/assimp/matrix4x4.h \
		../assimp/include/assimp/quaternion.h \
		../assimp/include/assimp/vector2.inl \
		../assimp/include/assimp/vector3.inl \
		../assimp/include/assimp/color4.inl \
		../assimp/include/assimp/matrix3x3.inl \
		../assimp/include/assimp/matrix4x4.inl \
		../assimp/include/assimp/MathFunctions.h \
		../assimp/include/assimp/quaternion.inl \
		../assimp/include/assimp/postprocess.h \
		../assimp/include/assimp/scene.h \
		../assimp/include/assimp/texture.h \
		../assimp/include/assimp/Compiler/pushpack1.h \
		../assimp/include/assimp/Compiler/poppack1.h \
		../assimp/include/assimp/mesh.h \
		../assimp/include/assimp/aabb.h \
		../assimp/include/assimp/light.h \
		../assimp/include/assimp/camera.h \
		../assimp/include/assimp/material.h \
		../assimp/include/assimp/material.inl \
		../assimp/include/assimp/anim.h \
		../assimp/include/assimp/metadata.h \
		../assimp/include/assimp/Compiler/pstdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

openglwindow.o: openglwindow.cpp openglwindow.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QOpenGLWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qopenglwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtguiglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobal.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig-bootstrapped.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qconfig.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtcore-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsystemdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qprocessordetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtypeinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsysinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlogging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qflags.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbasicatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qgenericatomic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qglobalstatic.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmutex.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnumeric.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qversiontagging.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtgui-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qtwidgets-config.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/QWidget \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qwidget.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qnamespace.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstring.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qchar.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrefcount.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qarraydata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringbuilder.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qalgorithms.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiterator.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhashfunctions.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpair.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qbytearraylist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringlist.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qregexp.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qstringmatcher.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcoreevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qscopedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmetatype.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qobject_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmargins.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpaintdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qrect.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsize.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qpoint.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpalette.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcolor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgb.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qrgba64.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qbrush.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvector.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qmatrix.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpolygon.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qregion.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdatastream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qiodevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qline.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtransform.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpainterpath.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qimage.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixelformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qpixmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qshareddata.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qhash.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfont.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontmetrics.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qfontinfo.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtWidgets/qsizepolicy.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qcursor.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qkeysequence.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qevent.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qvariant.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qmap.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qdebug.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qtextstream.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qlocale.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qset.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qurlquery.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfile.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qfiledevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qvector2d.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qtouchdevice.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QSurfaceFormat \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qsurfaceformat.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengl.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtCore/qt_windows.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopengles2ext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/qopenglext.h \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QKeyEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QMouseEvent \
		../../miniconda3/envs/isis5.0.1/include/qt/QtGui/QWheelEvent \
		modelmanager.h \
		../assimp/include/assimp/cimport.h \
		../assimp/include/assimp/importerdesc.h \
		../assimp/include/assimp/types.h \
		../assimp/include/assimp/defs.h \
		../assimp/build/include/assimp/config.h \
		../assimp/include/assimp/vector2.h \
		../assimp/include/assimp/vector3.h \
		../assimp/include/assimp/color4.h \
		../assimp/include/assimp/matrix3x3.h \
		../assimp/include/assimp/matrix4x4.h \
		../assimp/include/assimp/quaternion.h \
		../assimp/include/assimp/vector2.inl \
		../assimp/include/assimp/vector3.inl \
		../assimp/include/assimp/color4.inl \
		../assimp/include/assimp/matrix3x3.inl \
		../assimp/include/assimp/matrix4x4.inl \
		../assimp/include/assimp/MathFunctions.h \
		../assimp/include/assimp/quaternion.inl \
		../assimp/include/assimp/postprocess.h \
		../assimp/include/assimp/scene.h \
		../assimp/include/assimp/texture.h \
		../assimp/include/assimp/Compiler/pushpack1.h \
		../assimp/include/assimp/Compiler/poppack1.h \
		../assimp/include/assimp/mesh.h \
		../assimp/include/assimp/aabb.h \
		../assimp/include/assimp/light.h \
		../assimp/include/assimp/camera.h \
		../assimp/include/assimp/material.h \
		../assimp/include/assimp/material.inl \
		../assimp/include/assimp/anim.h \
		../assimp/include/assimp/metadata.h \
		../assimp/include/assimp/Compiler/pstdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglwindow.o openglwindow.cpp

modelmanager.o: modelmanager.cpp modelmanager.h \
		../assimp/include/assimp/cimport.h \
		../assimp/include/assimp/importerdesc.h \
		../assimp/include/assimp/types.h \
		../assimp/include/assimp/defs.h \
		../assimp/build/include/assimp/config.h \
		../assimp/include/assimp/vector2.h \
		../assimp/include/assimp/vector3.h \
		../assimp/include/assimp/color4.h \
		../assimp/include/assimp/matrix3x3.h \
		../assimp/include/assimp/matrix4x4.h \
		../assimp/include/assimp/quaternion.h \
		../assimp/include/assimp/vector2.inl \
		../assimp/include/assimp/vector3.inl \
		../assimp/include/assimp/color4.inl \
		../assimp/include/assimp/matrix3x3.inl \
		../assimp/include/assimp/matrix4x4.inl \
		../assimp/include/assimp/MathFunctions.h \
		../assimp/include/assimp/quaternion.inl \
		../assimp/include/assimp/postprocess.h \
		../assimp/include/assimp/scene.h \
		../assimp/include/assimp/texture.h \
		../assimp/include/assimp/Compiler/pushpack1.h \
		../assimp/include/assimp/Compiler/poppack1.h \
		../assimp/include/assimp/mesh.h \
		../assimp/include/assimp/aabb.h \
		../assimp/include/assimp/light.h \
		../assimp/include/assimp/camera.h \
		../assimp/include/assimp/material.h \
		../assimp/include/assimp/material.inl \
		../assimp/include/assimp/anim.h \
		../assimp/include/assimp/metadata.h \
		../assimp/include/assimp/Compiler/pstdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelmanager.o modelmanager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_openglwindow.o: moc_openglwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openglwindow.o moc_openglwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

